name: Terraform CI-CD pipeline
on:
  push:
    paths:
      - '**/*.tf'
      - '*.tfvars'
      - '.github/workflows/terraform-cicd.yaml'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '*.tfvars'
      - '.github/workflows/terraform-cicd.yaml'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  INFRACOST_API_KEY : ${{ secrets.INFRACOST_API_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform fmt
        uses: dflook/terraform-fmt-check@v2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Test
        uses: dflook/terraform-test@v2
        with:
          var_file: prod.tfvars

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Validate
        uses: dflook/terraform-validate@v2

  plan:
    if: github.event_name == 'pull_request'
    needs: [lint, test, validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dflook/terraform-plan@v2
        with:
          workspace: prod
          var_file: prod.tfvars
      - name: Cost Estimation
        run: |
          curl -s https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost breakdown --path . --format table

  apply:
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [lint, test, validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Apply
        uses: dflook/terraform-apply@v2
        with:
          workspace: prod
          var_file: prod.tfvars
